In [1]:
import pandas as pd
df = pd.read_csv('loans_full_schema.csv')
df

,emp_title,emp_length,state,homeownership,annual_income,verified_income,debt_to_income,annual_income_joint,verification_income_joint,debt_to_income_joint,...,sub_grade,issue_month,loan_status,initial_listing_status,disbursement_method,balance,paid_total,paid_principal,paid_interest,paid_late_fees
0,global config engineer,3.0,NJ,MORTGAGE,90000.0,Verified,18.01,NaN,NaN,NaN,...,C3,Mar-2018,Current,whole,Cash,27015.86,1999.33,984.14,1015.19,0.0
1,warehouse office clerk,10.0,HI,RENT,40000.0,Not Verified,5.04,NaN,NaN,NaN,...,C1,Feb-2018,Current,whole,Cash,4651.37,499.12,348.63,150.49,0.0
2,assembly,3.0,WI,RENT,40000.0,Source Verified,21.15,NaN,NaN,NaN,...,D1,Feb-2018,Current,fractional,Cash,1824.63,281.80,175.37,106.43,0.0
3,customer service,1.0,PA,RENT,30000.0,Not Verified,10.16,NaN,NaN,NaN,...,A3,Jan-2018,Current,whole,Cash,18853.26,3312.89,2746.74,566.15,0.0
4,security supervisor,10.0,CA,RENT,35000.0,Verified,57.96,57000.0,Verified,37.66,...,C3,Mar-2018,Current,whole,Cash,21430.15,2324.65,1569.85,754.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,owner,10.0,TX,RENT,108000.0,Source Verified,22.28,NaN,NaN,NaN,...,A4,Jan-2018,Current,whole,Cash,21586.34,2969.80,2413.66,556.14,0.0
9996,director,8.0,PA,MORTGAGE,121000.0,Verified,32.38,NaN,NaN,NaN,...,D3,Feb-2018,Current,whole,Cash,9147.44,1456.31,852.56,603.75,0.0
9997,toolmaker,10.0,CT,MORTGAGE,67000.0,Verified,45.26,107000.0,Source Verified,29.57,...,E2,Feb-2018,Current,fractional,Cash,27617.65,4620.80,2382.35,2238.45,0.0
9998,manager,1.0,WI,MORTGAGE,80000.0,Source Verified,11.99,NaN,NaN,NaN,...,A1,Feb-2018,Current,whole,Cash,21518.12,2873.31,2481.88,391.43,0.0
9999,operations analyst,3.0,CT,RENT,66000.0,Not Verified,20.82,NaN,NaN,NaN,...,B4,Feb-2018,Current,whole,Cash,11574.83,1658.56,1225.17,433.39,0.0

In [15]:
df.loc[:,['emp_title','emp_length']].isnull().mean()* 100

emp_title     8.33
emp_length    8.17
dtype: float64

## First feature with missing values is emp_title.
#I believe a good way to impute these values is with "Job title not given"

In [20]:
import numpy as np 

df['emp_title'] = np.where(df['emp_title'].isnull(), 'Job title not given', df['emp_title'])
df['emp_title'].head(1000)

0                       global config engineer
1                        warehouse office clerk
2                                      assembly
3                              customer service
4                          security supervisor
5                           Job title not given
6                                           hr
7                                        police
8                                         parts
9                                    4th person
10                                   supervisor
11                               register nurse
12       respiratory therapist & sleep lab tech
13                             senior inspector
14                          Job title not given
15                             dental hygienist
16                          Job title not given
17                              onsite medical
18                     operational risk manager
19                                       welder
20                    maintenance adm assistant
21                       warranty administrator
22                                  underwriter
23                          Job title not given
24                             program analyst
25                           surveyor/cadd tech
26                                  associated
27                 inventory control specialist
28                            inventory control
29               sr direct supoort professional
30                       director of operations
31                                  hospitalist
32                                      teacher
33                                   controller
34                                       deputy
35                    armed protection officer
36                                       driver
37                               supplies clerk
38                             loan consultant
39                             bank coordinator
40                          Job title not given
41                             senior recruiter
42                               reader advisor
43                                 truck driver
44                                        sales
45                 director of support services
46                                           rn
47                               police recruit
48                                  lead teller
49                             registered nurse
50                                 hes advisor
51                           sr admin assistant
52                                    president
53                              hvac technician
54                              nurse assistant
55                          Job title not given
56                                       driver
57                          gourmet food server
58                          Job title not given
59                              program manager
60                             deputy assessor
61                                 service tech
62                    senior technically writer
63                                           rn
64                               escrow manager
65                              quality control
66                  medical billing account rep
67                                 truck driver
68                              general manager
69                                    bartender
70                          Job title not given
71     interpreter/translator/school enrolment
72                  accounts receivable manager
73              asst to the director of theatre
74                                           rn
75                                    warehouse
76                          Job title not given
77                           operations manager
78                     administrative assistant
79                          composite tehnician
80                                          pta
81                             service director
82                                   it support
83                senior accounts payable clerk
84                                master driver
85                                      teacher
86                          physician assistant
87                               credit analyst
88                                          rca
89                      cabinet maker/installer
90                      benefits representative
91                                     mechanic
92          superintendent -customer operations
93                                       teller
94                          Job title not given
95                            territory manager
96                                  sr engineer
97                               office manager
98                          petroleum operator
99                                        owner
100                             project manager
101                        driver/crane opeator
102                               audit manager
103                                         cfo
104                                  qa auditor
105                                   line cook
106              supervisor of technical trades
107                                 crew chief
108                                       owner
109                               bus operator
110                               web developer
111                                    educator
112                         Job title not given
113                       construction manager
114                        education specialist
115                                         ceo
116                       account administrator
117                                      driver
118                         Job title not given
119                                     manager
120                        school administrator
121                                     qc lead
122                        planning supervisor
123                                  pipefitter
124                                       owner
125                      senior engagement lead
126                                    attorney
127                                 bank teller
128                     field service engineer
129             automotive service lane manager
130                    military officer captain
131                                         cpa
132                     home equity specialist
133                             general manager
134                         Job title not given
135                       accounting supervisor
136                            video management
137                          claims adjudicator
138                      head of product design
139                             project manager
140                                       sales
141              import booking and pricing rep
142                                receptionist
143               business analysis/csu manager
144                                  supervisor
145                         Job title not given
146                                       clerk
147                       formulation scientist
148                    documentation supervisor
149                      director of operations
150                        supply chain manager
151                         executive assistant
152                                shop foreman
153                         research technician
154                         Job title not given
155                        senior data engineer
156                              mechanic/owner
157                         Job title not given
158                 commercial insurance broker
159                 field operations supervisor
160                                      server
161                               hvac mechanic
162                         engineer assistant
163                      senior quality analyst
164                                  production
165                                 it director
166                         Job title not given
167                               sales manager
168                                       owner
169                    journeyman union plumber
170                         service technician
171                          executive director
172                                  management
173                                       sales
174                          customs specialist
175                             personal banker
176                       assistant controller
177               physical therapist assistant
178                  office manager/ bookkeeper
179                                       pilot
180                         service technician
181                         physician extender
182                             yard specialist
183                         Job title not given
184                                   bartender
185                              lease operator
186             dean of humanities and the arts
187                                          rn
188                                  instructor
189                                     manager
190                                       sales
191                             finance manager
192                            crisis counselor
193                 senior mechanical assembler
194                        maintenance director
195                         Job title not given
196                                  supervisor
197             microbiology labratory security
198                  telecommunications analyst
199                          medical secretary
200                financial service specialist
201                                  consultant
202                               cook / server
203                           business analyst
204                                        cook
205                              setup operator
206                         Job title not given
207                                     analyst
208                                 supervisor
209               research programmer / analyst
210                   rapid prototyping manager
211                           warehouse general
212                              pharmacy tech
213                          aviation inspector
214                         realtor / assistant
215                                  paralegal
216                                  accountant
217                                     cashier
218                                       owner
219                        contract specialist
220                         Job title not given
221                     chief financial officer
222                      officer of corporation
223                            kitchen designer
224                           regional manager
225                              executive chef
226                    telecommunications tech
227                                    finisher
228                          operations manager
229                               grocery clerk
230                                    mechanic
231                        services coordinator
232                         Job title not given
233                          renewal specialist
234                  associate medical director
235                         Job title not given
236                     junior graphic designer
237                               ceo president
238                            graphic designer
239                        accounting assistant
240                     group creative director
241                            forming operator
242                  large format printing lead
243                         Job title not given
244                         Job title not given
245                         technical sales rep
246                     pretreatment technician
247                          manager - projects
248                                 hydrologist
249                                  lieutenant
250                                    autocad
251                              office manager
252                        pharmacy technician
253                                  dockworker
254                                       sales
255              consulting database specialist
256                              house officer
257                                       vp hr
258                                     teacher
259                             shade assembler
260                                     finance
261                                   carpenter
262                                   counselor
263                               sales manager
264                   certified peer specialist
265                         Job title not given
266                                medical asst
267                         Job title not given
268                          production manager
269                                        cook
270                            maintenance tech
271                                     cleaner
272                                 pmo manager
273                         Job title not given
274                               manger/barber
275                         Job title not given
276                                     teacher
277                                   auto tech
278                         electronic engineer
279                   interior concept designer
280                            machine operator
281                                 dock worker
282                                   assistant
283                                 lead driver
284                     residential coordinator
285                         Job title not given
286                                 supervisor
287              assistant registrar-graduation
288              assistant to internet director
289                     family skill specialist
290                  head of shopper engagement
291                        shipping & receiving
292                                          rn
293                                     manager
294                                   managment
295                                     manager
296                      director of operations
297                             branch manager
298                               rural carrier
299                        office administrator
300                           regional director
301                                    educator
302                        fixed assets manager
303                                     manager
304                         Job title not given
305                                          rn
306                                hub employee
307    technical solutions architecture manager
308                                    dentist
309                               social worker
310                      service representative
311                       delivery merchandiser
312                                  physician
313                         executive assistant
314                                    attorney
315                                dietary aide
316                         engineer departnent
317                         nurse practitioner
318                                    cashier
319                                  principal
320                                    manager
321                                         fbc
322                              shipping clerk
323                         claims investigator
324                  executive customer service
325                      engineering supervisor
326                               administrator
327                         Job title not given
328                             legal assistant
329                            registered nurse
330                              deputy sheriff
331                             project manager
332                     lead software architect
333                                       sales
334                            ir technologist
335                               engineer tech
336                              owner/operator
337                                     manager
338                                       sales
339                                   carpenter
340                                sales manger
341                          claims examiner ii
342                     patternmaker / designer
343                              senior chemist
344                      civil engineering tech
345                          operations manager
346                              owner operator
347         district technology support analyst
348                           sr rest engineer
349                                       owner
350                                        chef
351                                receptionist
352                                     manager
353                                     manager
354                              office manager
355                    patient care coordinator
356                                    sergeant
357                              personal asst
358                               stylist/owner
359                            registered nurse
360                         executive assistant
361                           territory manager
362                           welder/fabricator
363                           solutions manager
364                           health technician
365                         Job title not given
366                                  hr analyst
367                                      editor
368                             account manager
369                                loan analyst
370             senior research project manager
371                                  senior dba
372                                   paralegal
373                           pr representative
374                                     teacher
375                         Job title not given
376                                truck driver
377                                  manager ii
378                                hr data tech
379                         department mananger
380                         supervisory auditor
381                         research specialist
382                                 firefighter
383                                 book keeper
384                              direct support
385                    business systems analyst
386                                     teacher
387              business development associate
388                                       owner
389                                       owner
390                          compliance manager
391            inventory specialist, purchasing
392                         Job title not given
393                               legal advisor
394                     disclosure specialists
395                          sr program manager
396                                 accountant
397                                   marketing
398                              beauty stylist
399                  transportation/ cdl driver
400                            security officer
401                      warranty administrator
402                             financial clerk
403                         Job title not given
404                              safety monitor
405                              civil engineer
406                                      roofer
407                             general manager
408                enterprise account executive
409                                     painter
410                       program support clerk
411                community development manger
412                                   installer
413                                      teller
414                                     laborer
415                         Job title not given
416                                      driver

In [22]:
filt = (df['emp_title'] ==  "Job title not given")
df.loc[filt]

,emp_title,emp_length,state,homeownership,annual_income,verified_income,debt_to_income,annual_income_joint,verification_income_joint,debt_to_income_joint,...,sub_grade,issue_month,loan_status,initial_listing_status,disbursement_method,balance,paid_total,paid_principal,paid_interest,paid_late_fees
5,Job title not given,NaN,KY,OWN,34000.00,Not Verified,6.46,NaN,NaN,NaN,...,A3,Jan-2018,Current,whole,Cash,4256.71,873.130000,743.29,129.84,0.00
14,Job title not given,NaN,FL,MORTGAGE,17000.00,Verified,33.98,NaN,NaN,NaN,...,D3,Jan-2018,Current,whole,Cash,2744.21,454.360000,255.79,198.57,0.00
16,Job title not given,NaN,NV,MORTGAGE,60000.00,Not Verified,31.22,NaN,NaN,NaN,...,D3,Jan-2018,Current,whole,Cash,11374.52,1532.080000,625.48,906.60,0.00
23,Job title not given,NaN,TX,MORTGAGE,40280.00,Verified,7.27,NaN,NaN,NaN,...,A3,Mar-2018,Current,whole,Cash,3323.42,223.710000,176.58,47.13,0.00
40,Job title not given,NaN,MI,MORTGAGE,19000.00,Not Verified,24.79,43000.00,Not Verified,17.15,...,D2,Jan-2018,Current,whole,Cash,9465.30,1261.320000,534.70,726.62,0.00
55,Job title not given,NaN,FL,OWN,22000.00,Source Verified,13.05,40000.00,Source Verified,22.39,...,D1,Mar-2018,Current,whole,Cash,1842.26,139.020000,82.74,56.28,0.00
58,Job title not given,NaN,NV,MORTGAGE,76000.00,Not Verified,14.62,NaN,NaN,NaN,...,A3,Jan-2018,Current,whole,Cash,5391.31,736.880000,608.69,128.19,0.00
70,Job title not given,NaN,DE,OWN,32000.00,Source Verified,22.09,NaN,NaN,NaN,...,D1,Mar-2018,Current,whole,Cash,8976.73,1014.930000,623.27,391.66,0.00
76,Job title not given,NaN,OR,RENT,13930.00,Verified,21.94,NaN,NaN,NaN,...,B4,Jan-2018,Current,fractional,Cash,3695.17,672.660000,504.83,167.83,0.00
94,Job title not given,NaN,MN,RENT,55000.00,Not Verified,12.22,NaN,NaN,NaN,...,D2,Jan-2018,Current,whole,Cash,14197.97,1891.950000,802.03,1089.92,0.00
112,Job title not given,NaN,WY,RENT,31812.00,Not Verified,37.83,NaN,NaN,NaN,...,D5,Feb-2018,Current,whole,Cash,9715.10,838.160000,284.90,553.26,0.00
118,Job title not given,NaN,MO,MORTGAGE,30784.00,Verified,27.56,66292.00,Verified,38.41,...,E2,Feb-2018,Current,fractional,Cash,5776.61,966.400000,498.39,468.01,0.00
134,Job title not given,NaN,TX,OWN,17000.00,Not Verified,27.68,78000.00,Not Verified,34.60,...,C4,Jan-2018,Current,whole,Cash,1927.12,453.420000,322.88,130.54,0.00
145,Job title not given,NaN,NY,OWN,42000.00,Verified,14.40,NaN,NaN,NaN,...,D5,Feb-2018,Current,whole,Cash,9612.44,1080.400000,387.56,692.84,0.00
154,Job title not given,NaN,AZ,RENT,0.00,Not Verified,NaN,167250.00,Not Verified,14.92,...,D1,Feb-2018,Current,whole,Cash,19128.86,1944.610000,871.14,1073.47,0.00
157,Job title not given,NaN,TN,OWN,50000.00,Source Verified,14.16,NaN,NaN,NaN,...,B2,Mar-2018,Current,whole,Cash,18550.28,1922.780000,1449.72,473.06,0.00
166,Job title not given,NaN,TX,MORTGAGE,65000.00,Not Verified,10.62,NaN,NaN,NaN,...,B2,Mar-2018,Current,whole,Cash,24350.26,1046.620000,649.74,396.88,0.00
183,Job title not given,NaN,NC,RENT,44088.00,Not Verified,27.93,NaN,NaN,NaN,...,C2,Feb-2018,Current,fractional,Cash,9078.33,1351.610000,921.67,429.94,0.00
195,Job title not given,NaN,NJ,MORTGAGE,82000.00,Verified,18.09,NaN,NaN,NaN,...,D3,Feb-2018,Current,fractional,Cash,18294.92,2912.580000,1705.08,1207.50,0.00
206,Job title not given,NaN,AL,RENT,16000.00,Verified,25.43,NaN,NaN,NaN,...,D2,Feb-2018,Current,whole,Cash,6394.79,1006.100000,605.21,400.89,0.00
220,Job title not given,NaN,TX,MORTGAGE,20000.00,Source Verified,0.00,NaN,NaN,NaN,...,B2,Mar-2018,Current,whole,Cash,9608.54,652.780000,391.46,261.32,0.00
232,Job title not given,NaN,MA,MORTGAGE,145000.00,Not Verified,16.57,NaN,NaN,NaN,...,A1,Feb-2018,Current,whole,Cash,13839.02,1350.560000,1160.98,189.58,0.00
235,Job title not given,NaN,NE,RENT,35000.00,Source Verified,5.59,NaN,NaN,NaN,...,C1,Jan-2018,Current,whole,Cash,2719.66,400.060000,280.34,119.72,0.00
243,Job title not given,NaN,CA,MORTGAGE,130000.00,Not Verified,14.43,NaN,NaN,NaN,...,A2,Mar-2018,Current,whole,Cash,13851.40,1365.370000,1148.60,216.77,0.00
244,Job title not given,NaN,UT,OWN,56000.00,Source Verified,16.08,NaN,NaN,NaN,...,A1,Feb-2018,Current,whole,DirectPay,10310.60,1378.300000,1189.40,188.90,0.00
265,Job title not given,NaN,PA,RENT,9600.00,Source Verified,20.73,NaN,NaN,NaN,...,D1,Mar-2018,Current,fractional,Cash,4675.37,517.220000,324.63,192.59,0.00
267,Job title not given,NaN,NJ,MORTGAGE,12036.00,Verified,74.38,134536.00,Verified,14.93,...,A3,Jan-2018,Current,whole,Cash,438.66,784.050000,761.34,22.71,0.00
273,Job title not given,NaN,TN,RENT,20400.00,Verified,9.82,NaN,NaN,NaN,...,A5,Mar-2018,Current,fractional,Cash,9504.67,630.790000,495.33,135.46,0.00
275,Job title not given,NaN,CO,MORTGAGE,65318.52,Not Verified,22.18,NaN,NaN,NaN,...,C4,Mar-2018,Current,whole,Cash,24143.51,1744.060000,856.49,887.57,0.00
285,Job title not given,NaN,CA,MORTGAGE,40000.00,Verified,7.20,NaN,NaN,NaN,...,D1,Mar-2018,Current,whole,Cash,14518.41,1115.210000,481.59,633.62,0.00
304,Job title not given,NaN,PA,MORTGAGE,31000.00,Not Verified,17.96,NaN,NaN,NaN,...,C5,Feb-2018,Current,whole,Cash,13532.58,1009.140000,467.42,541.72,0.00
327,Job title not given,NaN,FL,MORTGAGE,13800.00,Verified,128.61,52800.00,Verified,34.23,...,D3,Jan-2018,Current,fractional,Cash,3213.28,652.490000,386.72,265.77,0.00
365,Job title not given,NaN,MD,MORTGAGE,56000.00,Not Verified,19.95,NaN,NaN,NaN,...,A5,Jan-2018,Current,whole,Cash,17039.55,3041.430000,2435.45,605.98,0.00
375,Job title not given,NaN,OH,MORTGAGE,24000.00,Verified,35.50,NaN,NaN,NaN,...,C5,Feb-2018,Current,whole,Cash,14327.76,1432.760000,672.24,760.52,0.00
392,Job title not given,NaN,MI,OWN,14000.00,Source Verified,17.67,NaN,NaN,NaN,...,A3,Jan-2018,Current,fractional,Cash,7419.11,1303.680000,1080.89,222.79,0.00
403,Job title not given,NaN,MD,RENT,31000.00,Verified,25.18,NaN,NaN,NaN,...,A5,Jan-2018,Current,fractional,Cash,6999.51,1249.410000,1000.49,248.92,0.00
415,Job title not given,NaN,IL,MORTGAGE,23000.00,Verified,22.66,NaN,NaN,NaN,...,E1,Feb-2018,Current,fractional,Cash,13791.64,2281.620000,1208.36,1073.26,0.00
420,Job title not given,NaN,CA,RENT,75000.00,Verified,17.74,NaN,NaN,NaN,...,B2,Feb-2018,Current,whole,Cash,33390.90,3509.450000,2609.10,900.35,0.00
424,Job title not given,NaN,NJ,RENT,63000.00,Not Verified,35.12,NaN,NaN,NaN,...,C5,Mar-2018,Current,whole,Cash,14499.17,1067.900000,500.83,567.07,0.00
433,Job title not given,NaN,UT,OWN,10800.00,Verified,92.67,61800.00,Verified,18.41,...,C4,Feb-2018,Current,whole,Cash,19080.90,1888.600000,919.10,969.50,0.00
440,Job title not given,NaN,LA,OWN,37000.00,Not Verified,37.46,NaN,NaN,NaN,...,B4,Mar-2018,Current,whole,Cash,17122.43,1164.380000,852.57,311.81,0.00
465,Job title not given,NaN,CA,RENT,25000.00,Source Verified,9.84,NaN,NaN,NaN,...,D1,Jan-2018,Current,fractional,DirectPay,6138.35,1218.500000,761.65,456.85,0.00
477,Job title not given,NaN,AZ,RENT,75000.00,Verified,32.86,NaN,NaN,NaN,...,D2,Feb-2018,Current,fractional,Cash,6851.56,1070.430000,648.44,421.99,0.00
494,Job title not given,NaN,IL,MORTGAGE,35000.00,Source Verified,10.67,NaN,NaN,NaN,...,D5,Feb-2018,Current,whole,Cash,11539.98,1307.070000,460.02,847.05,0.00
536,Job title not given,NaN,OH,OWN,34000.00,Not Verified,15.81,NaN,NaN,NaN,...,C2,Feb-2018,Current,whole,Cash,10893.83,1562.870000,1106.17,456.70,0.00
546,Job title not given,NaN,CA,RENT,25000.00,Not Verified,14.31,NaN,NaN,NaN,...,B2,Jan-2018,Current,fractional,Cash,8342.92,1525.910000,1157.08,368.83,0.00
560,Job title not given,NaN,CA,OWN,78000.00,Not Verified,20.28,NaN,NaN,NaN,...,A2,Feb-2018,Current,whole,Cash,13464.86,1817.390000,1535.14,282.25,0.00
576,Job title not given,NaN,MS,OWN,22212.00,Source Verified,9.08,NaN,NaN,NaN,...,C1,Jan-2018,Current,fractional,Cash,4532.79,666.730000,467.21,199.52,0.00
586,Job title not given,NaN,AL,RENT,22000.00,Verified,11.24,NaN,NaN,NaN,...,B4,Mar-2018,Current,whole,Cash,6499.71,682.280000,500.29,181.99,0.00
593,Job title not given,NaN,GA,MORTGAGE,17200.00,Not Verified,20.96,32130.00,Not Verified,11.22,...,C4,Feb-2018,Current,fractional,Cash,8665.10,1313.760000,859.90,453.86,0.00
613,Job title not given,NaN,MS,RENT,28750.00,Not Verified,37.95,NaN,NaN,NaN,...,C2,Feb-2018,Current,whole,DirectPay,14284.05,1383.410000,715.95,667.46,0.00
651,Job title not given,NaN,CA,RENT,14200.00,Verified,36.35,NaN,NaN,NaN,...,A5,Jan-2018,Current,whole,Cash,1647.05,412.360000,352.95,59.41,0.00
653,Job title not given,NaN,AZ,RENT,25875.00,Not Verified,6.65,NaN,NaN,NaN,...,A5,Feb-2018,Current,whole,Cash,6940.89,701.350000,559.11,142.24,0.00
665,Job title not given,NaN,OR,OWN,72276.00,Source Verified,16.24,NaN,NaN,NaN,...,A1,Feb-2018,Current,whole,Cash,8517.56,1138.780000,982.44,156.34,0.00
707,Job title not given,NaN,NY,OWN,20000.00,Not Verified,15.97,NaN,NaN,NaN,...,B5,Feb-2018,Current,whole,Cash,9057.25,1321.740000,942.75,378.99,0.00
716,Job title not given,NaN,OH,OWN,42000.00,Not Verified,20.23,NaN,NaN,NaN,...,C4,Mar-2018,Current,whole,Cash,9554.19,685.340000,445.81,239.53,0.00
750,Job title not given,NaN,NJ,RENT,32000.00,Verified,0.94,NaN,NaN,NaN,...,B5,Feb-2018,Current,whole,Cash,4528.63,655.870000,471.37,184.50,0.00
756,Job title not given,NaN,IL,MORTGAGE,20000.00,Verified,17.47,NaN,NaN,NaN,...,C3,Feb-2018,Current,whole,Cash,3633.87,541.220000,366.13,175.09,0.00
770,Job title not given,NaN,NY,MORTGAGE,84000.00,Not Verified,20.70,NaN,NaN,NaN,...,D3,Feb-2018,Current,whole,Cash,15338.12,1644.360000,661.88,982.48,0.00
803,Job title not given,NaN,WA,OWN,24000.00,Source Verified,5.92,NaN,NaN,NaN,...,B5,Jan-2018,Current,whole,Cash,6170.96,1157.690000,829.04,328.65,0.00
806,Job title not given,NaN,OH,RENT,24000.00,Not Verified,23.30,NaN,NaN,NaN,...,B2,Mar-2018,Current,whole,Cash,7420.10,795.570000,579.90,215.67,0.00
808,Job title not given,NaN,FL,OWN,40012.00,Verified,17.43,NaN,NaN,NaN,...,A4,Mar-2018,Current,whole,Cash,8994.16,1208.700000,1005.84,202.86,0.00
822,Job title not given,NaN,OH,MORTGAGE,10000.00,Not Verified,144.30,335000.00,Not Verified,10.93,...,B2,Jan-2018,Current,whole,Cash,37369.27,4220.480000,2630.73,1589.75,0.00
824,Job title not given,NaN,WI,RENT,12276.00,Verified,26.78,NaN,NaN,NaN,...,C3,Jan-2018,Current,fractional,Cash,3539.64,676.530000,460.36,216.17,0.00
835,Job title not given,NaN,CA,RENT,52755.00,Verified,35.08,102258.00,Verified,22.16,...,B5,Feb-2018,Current,whole,Cash,23756.73,2190.650000,1243.27,947.38,0.00
848,Job title not given,NaN,NJ,RENT,20000.00,Not Verified,9.90,NaN,NaN,NaN,...,D1,Jan-2018,Current,fractional,Cash,2668.83,529.800000,331.17,198.63,0.00
859,Job title not given,NaN,VA,RENT,59000.00,Verified,23.56,NaN,NaN,NaN,...,C3,Mar-2018,Current,whole,Cash,27952.38,3055.600000,2047.62,1007.98,0.00
894,Job title not given,NaN,VA,RENT,35000.00,Source Verified,11.56,NaN,NaN,NaN,...,B2,Mar-2018,Current,fractional,Cash,10202.65,1057.540000,797.35,260.19,0.00
895,Job title not given,NaN,IL,OWN,72000.00,Not Verified,10.53,NaN,NaN,NaN,...,C1,Mar-2018,Current,whole,Cash,25117.49,2695.120000,1882.51,812.61,0.00
899,Job title not given,NaN,CA,OWN,45001.00,Not Verified,11.52,NaN,NaN,NaN,...,D4,Mar-2018,Current,whole,Cash,16881.16,1997.200000,1118.84,878.36,0.00
924,Job title not given,NaN,CA,RENT,36051.00,Not Verified,17.51,NaN,NaN,NaN,...,A5,Jan-2018,Current,whole,DirectPay,2000.00,4139.050000,4000.00,139.05,0.00
927,Job title not given,NaN,IN,RENT,0.00,Not Verified,NaN,28000.00,Not Verified,5.61,...,B3,Mar-2018,Current,whole,Cash,4825.70,525.950000,374.30,151.65,0.00
997,Job title not given,NaN,MI,MORTGAGE,70000.00,Not Verified,3.91,NaN,NaN,NaN,...,A1,Mar-2018,Current,whole,Cash,14761.63,1475.990000,1238.37,237.62,0.00
1010,Job title not given,NaN,CA,MORTGAGE,11000.00,Verified,42.25,146000.00,Verified,6.60,...,A5,Jan-2018,Current,whole,Cash,13999.08,2491.680000,2000.92,490.76,0.00
1042,Job title not given,NaN,CA,RENT,55000.00,Source Verified,21.89,NaN,NaN,NaN,...,D5,Feb-2018,Current,whole,Cash,19224.93,2160.770000,775.07,1385.70,0.00
1061,Job title not given,NaN,CA,RENT,13164.00,Verified,4.56,NaN,NaN,NaN,...,A5,Jan-2018,Current,whole,Cash,5687.13,1015.120000,812.87,202.25,0.00
1068,Job title not given,NaN,FL,RENT,45000.00,Source Verified,24.67,NaN,NaN,NaN,...,B3,Jan-2018,Current,fractional,Cash,8790.09,1611.670000,1209.91,401.76,0.00
1105,Job title not given,NaN,IN,RENT,32800.00,Not Verified,29.09,NaN,NaN,NaN,...,A4,Feb-2018,Fully Paid,whole,Cash,0.00,3888.056465,3800.00,88.06,0.00
1130,Job title not given,NaN,CA,MORTGAGE,70000.00,Verified,39.43,130000.00,Verified,23.47,...,D1,Jan-2018,Fully Paid,whole,Cash,0.00,16272.547158,16000.00,272.55,0.00
1133,Job title not given,NaN,SC,MORTGAGE,118000.00,Verified,16.08,NaN,NaN,NaN,...,B5,Feb-2018,Current,whole,Cash,38010.26,3530.900000,1989.74,1541.16,0.00
1147,Job title not given,NaN,SC,MORTGAGE,125000.00,Source Verified,6.15,NaN,NaN,NaN,...,D2,Mar-2018,Current,whole,Cash,33905.61,2620.360000,1094.39,1525.97,0.00
1166,Job title not given,NaN,GA,RENT,25700.00,Not Verified,17.98,NaN,NaN,NaN,...,A2,Jan-2018,Current,whole,Cash,3851.16,1263.140000,1148.84,114.30,0.00
1169,Job title not given,NaN,MO,RENT,55000.00,Not Verified,30.87,NaN,NaN,NaN,...,A2,Mar-2018,Current,whole,Cash,11388.95,747.090000,611.05,136.04,0.00
1174,Job title not given,NaN,GA,OWN,32844.00,Source Verified,20.94,61416.00,Source Verified,25.95,...,C4,Jan-2018,Current,whole,Cash,3184.01,488.610000,315.99,172.62,0.00
1185,Job title not given,NaN,GA,OWN,50000.00,Not Verified,24.11,NaN,NaN,NaN,...,A3,Mar-2018,Current,whole,DirectPay,11089.41,1097.870000,910.59,187.28,0.00
1191,Job title not given,NaN,AR,RENT,60000.00,Not Verified,16.32,NaN,NaN,NaN,...,A2,Jan-2018,Current,whole,Cash,15691.48,2735.170000,2308.52,426.65,0.00
1197,Job title not given,NaN,WV,MORTGAGE,110000.00,Not Verified,19.40,NaN,NaN,NaN,...,B2,Jan-2018,Current,whole,Cash,7025.61,1284.990000,974.39,310.60,0.00
1207,Job title not given,NaN,CA,MORTGAGE,72000.00,Verified,25.20,NaN,NaN,NaN,...,C2,Jan-2018,Current,fractional,Cash,4420.65,817.410000,579.35,238.06,0.00
1220,Job title not given,NaN,CO,RENT,37000.00,Verified,36.72,94000.00,Verified,16.07,...,C3,Feb-2018,Current,whole,Cash,22868.93,2218.990000,1131.07,1087.92,0.00
1240,Job title not given,NaN,MO,MORTGAGE,75000.00,Not Verified,22.54,115000.00,Not Verified,23.89,...,A2,Feb-2018,Current,whole,Cash,7849.13,773.710000,650.87,122.84,0.00
1242,Job title not given,NaN,WA,RENT,25000.00,Not Verified,27.70,NaN,NaN,NaN,...,C1,Mar-2018,Current,fractional,Cash,7630.08,524.910000,369.92,154.99,0.00
1244,Job title not given,NaN,ID,OWN,72000.00,Verified,25.96,NaN,NaN,NaN,...,C1,Jan-2018,Current,fractional,Cash,30890.38,5815.420000,4109.62,1705.80,0.00
1247,Job title not given,NaN,GA,MORTGAGE,72000.00,Verified,20.10,NaN,NaN,NaN,...,B1,Jan-2018,Current,whole,Cash,10528.97,1907.710000,1471.03,436.68,0.00
1248,Job title not given,NaN,MD,MORTGAGE,95000.00,Not Verified,22.33,NaN,NaN,NaN,...,A2,Jan-2018,Current,whole,Cash,8717.45,1519.570000,1282.55,237.02,0.00
1251,Job title not given,NaN,NE,OWN,25000.00,Source Verified,20.07,NaN,NaN,NaN,...,C3,Mar-2018,Current,whole,Cash,7826.66,855.570000,573.34,282.23,0.00
1253,Job title not given,NaN,NC,RENT,24000.00,Source Verified,5.50,NaN,NaN,NaN,...,A5,Jan-2018,Current,whole,Cash,3149.76,562.260000,450.24,112.02,0.00
1255,Job title not given,NaN,OK,MORTGAGE,0.00,Not Verified,NaN,150000.00,Not Verified,13.81,...,D1,Mar-2018,Current,fractional,Cash,23229.44,1761.060000,770.56,990.50,0.00
1262,Job title not given,NaN,MI,MORTGAGE,47000.00,Verified,3.93,NaN,NaN,NaN,...,B2,Mar-2018,Current,whole,Cash,5565.08,576.830000,434.92,141.91,0.00
1277,Job title not given,NaN,TX,MORTGAGE,68750.00,Not Verified,33.92,116750.00,Not Verified,22.98,...,A5,Jan-2018,Current,whole,Cash,12514.86,2942.560000,2485.14,457.42,0.00
1302,Job title not given,NaN,PA,OWN,23000.00,Not Verified,13.73,48000.00,Not Verified,15.95,...,D4,Mar-2018,Current,whole,Cash,937.82,104.750000,62.18,42.57,0.00
1306,Job title not given,NaN,AZ,MORTGAGE,18000.00,Verified,10.09,NaN,NaN,NaN,...,D1,Mar-2018,Current,whole,DirectPay,9570.30,708.050000,429.70,278.35,0.00
1330,Job title not given,NaN,WA,MORTGAGE,0.00,Not Verified,NaN,84000.00,Not Verified,17.43,...,A4,Feb-2018,Current,whole,Cash,13872.03,1390.590000,1127.97,262.62,0.00
1356,Job title not given,NaN,GA,MORTGAGE,30000.00,Not Verified,17.00,NaN,NaN,NaN,...,B1,Feb-2018,Current,whole,Cash,14204.31,1242.630000,795.69,446.94,0.00
1378,Job title not given,NaN,TX,MORTGAGE,190000.00,Source Verified,10.67,NaN,NaN,NaN,...,A3,Mar-2018,Current,whole,Cash,32344.12,3215.160000,2655.88,559.28,0.00
1438,Job title not given,NaN,CT,RENT,28790.00,Not Verified,20.84,59990.00,Not Verified,10.00,...,B4,Jan-2018,Current,whole,Cash,15836.57,2986.340000,2163.43,822.91,0.00
1449,Job title not given,NaN,NY,MORTGAGE,67846.00,Not Verified,11.53,NaN,NaN,NaN,...,A4,Jan-2018,Current,whole,Cash,2184.72,385.960000,315.28,70.68,0.00
1459,Job title not given,NaN,WA,RENT,42000.00,Not Verified,17.63,NaN,NaN,NaN,...,C2,Jan-2018,Current,whole,Cash,15030.26,2862.580000,1969.74,892.84,0.00
1468,Job title not given,NaN,OK,OWN,41969.00,Source Verified,6.63,76289.00,Source Verified,7.14,...,C5,Feb-2018,Current,whole,Cash,6376.78,972.220000,623.22,349.00,0.00
1483,Job title not given,NaN,NJ,OWN,24000.00,Not Verified,23.20,NaN,NaN,NaN,...,D2,Feb-2018,Current,whole,Cash,11495.84,1218.380000,504.16,714.22,0.00
1486,Job title not given,NaN,CA,RENT,85500.00,Not Verified,6.58,171000.00,Not Verified,7.85,...,C2,Jan-2018,Current,whole,Cash,27790.51,3835.800000,2209.49,1626.31,0.00
1487,Job title not given,NaN,MA,RENT,27000.00,Verified,5.61,NaN,NaN,NaN,...,C4,Jan-2018,Current,fractional,Cash,7277.81,1103.390000,722.19,381.20,0.00
1488,Job title not given,NaN,CA,OWN,120000.00,Verified,16.00,242000.00,Verified,32.70,...,A4,Mar-2018,Current,whole,Cash,38328.35,2379.160000,1671.65,707.51,0.00
1500,Job title not given,NaN,IL,MORTGAGE,55000.00,Not Verified,18.68,NaN,NaN,NaN,...,A3,Mar-2018,Current,whole,Cash,13861.74,1377.950000,1138.26,239.69,0.00
1502,Job title not given,NaN,IL,OWN,43000.00,Not Verified,31.37,NaN,NaN,NaN,...,D1,Mar-2018,Current,fractional,Cash,4675.37,528.610000,324.63,203.98,0.00
1535,Job title not given,NaN,SC,OWN,68186.00,Not Verified,15.61,NaN,NaN,NaN,...,D1,Mar-2018,Current,whole,Cash,11614.70,892.190000,385.30,506.89,0.00
1536,Job title not given,NaN,NY,RENT,15500.00,Verified,16.11,NaN,NaN,NaN,...,C3,Feb-2018,Current,whole,DirectPay,6360.23,952.600000,639.77,312.83,0.00
1561,Job title not given,NaN,TX,MORTGAGE,30000.00,Source Verified,16.52,NaN,NaN,NaN,...,C4,Jan-2018,Current,whole,Cash,13645.89,2106.490000,1354.11,752.38,0.00
1578,Job title not given,NaN,FL,MORTGAGE,53695.00,Not Verified,17.14,NaN,NaN,NaN,...,C2,Mar-2018,Current,fractional,Cash,9312.56,959.890000,687.44,272.45,0.00
1604,Job title not given,NaN,LA,RENT,13000.00,Verified,9.51,NaN,NaN,NaN,...,A3,Jan-2018,Current,whole,Cash,4364.17,754.750000,635.83,118.92,0.00
1633,Job title not given,NaN,NH,MORTGAGE,52000.00,Not Verified,19.85,NaN,NaN,NaN,...,C1,Mar-2018,Current,whole,Cash,15612.50,749.760000,387.50,362.26,0.00
1640,Job title not given,NaN,NC,RENT,18960.00,Not Verified,15.19,NaN,NaN,NaN,...,A2,Feb-2018,Current,whole,Cash,3141.78,424.080000,358.22,65.86,0.00
1653,Job title not given,NaN,IL,RENT,0.00,Not Verified,NaN,74000.00,Not Verified,30.63,...,D4,Mar-2018,Current,whole,Cash,28510.40,3373.050000,1889.60,1483.45,0.00
1664,Job title not given,NaN,MO,RENT,24000.00,Not Verified,25.10,NaN,NaN,NaN,...,C2,Jan-2018,Current,whole,Cash,4539.23,700.360000,460.77,239.59,0.00
1668,Job title not given,NaN,AR,MORTGAGE,40000.00,Source Verified,15.21,NaN,NaN,NaN,...,C1,Feb-2018,Current,whole,Cash,14265.96,1332.530000,734.04,598.49,0.00
1676,Job title not given,NaN,CA,OWN,30000.00,Source Verified,5.92,NaN,NaN,NaN,...,B3,Mar-2018,Current,whole,Cash,9280.21,968.050000,719.79,248.26,0.00
1685,Job title not given,NaN,CO,MORTGAGE,30000.00,Not Verified,3.88,NaN,NaN,NaN,...,B1,Jan-2018,Current,fractional,Cash,2193.45,398.790000,306.55,92.24,0.00

In [31]:
df['months_since_last_delinq']

0       38.0
1        NaN
2       28.0
3        NaN
4        NaN
        ...
9995     NaN
9996     9.0
9997     6.0
9998     NaN
9999     NaN
Name: months_since_last_delinq, Length: 10000, dtype: float64

In [33]:
df['months_since_last_delinq'].max() #max is 188 so this will be our imputed value.
#loan['mths_since_last_delinq'] = np.where(loan['mths_since_last_delinq'].isnull(), 188, loan['mths_since_last_delinq'])

118.0

In [36]:
df['months_since_last_delinq'] = np.where(df['months_since_last_delinq'].isnull(),118,  df['months_since_last_delinq'])
df['months_since_last_delinq']

0        38.0
1       118.0
2        28.0
3       118.0
4       118.0
        ...
9995    118.0
9996      9.0
9997      6.0
9998    118.0
9999    118.0
Name: months_since_last_delinq, Length: 10000, dtype: float64

In [37]:
 filt = (df['months_since_last_delinq'] == 118)
df.loc[filt]

,emp_title,emp_length,state,homeownership,annual_income,verified_income,debt_to_income,annual_income_joint,verification_income_joint,debt_to_income_joint,...,sub_grade,issue_month,loan_status,initial_listing_status,disbursement_method,balance,paid_total,paid_principal,paid_interest,paid_late_fees
1,warehouse office clerk,10.0,HI,RENT,40000.0,Not Verified,5.04,NaN,NaN,NaN,...,C1,Feb-2018,Current,whole,Cash,4651.37,499.12,348.63,150.49,0.0
3,customer service,1.0,PA,RENT,30000.0,Not Verified,10.16,NaN,NaN,NaN,...,A3,Jan-2018,Current,whole,Cash,18853.26,3312.89,2746.74,566.15,0.0
4,security supervisor,10.0,CA,RENT,35000.0,Verified,57.96,57000.0,Verified,37.66,...,C3,Mar-2018,Current,whole,Cash,21430.15,2324.65,1569.85,754.80,0.0
6,hr,10.0,MI,MORTGAGE,35000.0,Source Verified,23.66,155000.0,Not Verified,13.12,...,C2,Jan-2018,Current,whole,Cash,22560.00,2730.51,1440.00,1290.51,0.0
9,4th person,3.0,IL,RENT,30000.0,Not Verified,18.91,NaN,NaN,NaN,...,A3,Mar-2018,Current,fractional,Cash,6077.13,391.15,322.87,68.28,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,program director,5.0,NY,RENT,70000.0,Not Verified,15.31,NaN,NaN,NaN,...,B2,Jan-2018,Current,whole,DirectPay,21487.30,2426.81,1512.70,914.11,0.0
9993,service advisor,0.0,NC,MORTGAGE,20000.0,Source Verified,23.23,NaN,NaN,NaN,...,A5,Jan-2018,Current,whole,Cash,4374.69,778.67,625.31,153.36,0.0
9995,owner,10.0,TX,RENT,108000.0,Source Verified,22.28,NaN,NaN,NaN,...,A4,Jan-2018,Current,whole,Cash,21586.34,2969.80,2413.66,556.14,0.0
9998,manager,1.0,WI,MORTGAGE,80000.0,Source Verified,11.99,NaN,NaN,NaN,...,A1,Feb-2018,Current,whole,Cash,21518.12,2873.31,2481.88,391.43,0.0
9999,operations analyst,3.0,CT,RENT,66000.0,Not Verified,20.82,NaN,NaN,NaN,...,B4,Feb-2018,Current,whole,Cash,11574.83,1658.56,1225.17,433.39,0.0

In [42]:
df.isnull().mean()*100

emp_title                            0.00
emp_length                           8.17
state                                0.00
homeownership                        0.00
annual_income                        0.00
verified_income                      0.00
debt_to_income                       0.24
annual_income_joint                 85.05
verification_income_joint           85.45
debt_to_income_joint                85.05
delinq_2y                            0.00
months_since_last_delinq             0.00
earliest_credit_line                 0.00
inquiries_last_12m                   0.00
total_credit_lines                   0.00
open_credit_lines                    0.00
total_credit_limit                   0.00
total_credit_utilized                0.00
num_collections_last_12m             0.00
num_historical_failed_to_pay         0.00
months_since_90d_late               77.15
current_accounts_delinq              0.00
total_collection_amount_ever         0.00
current_installment_accounts         0.00
accounts_opened_24m                  0.00
months_since_last_credit_inquiry    12.71
num_satisfactory_accounts            0.00
num_accounts_120d_past_due           3.18
num_accounts_30d_past_due            0.00
num_active_debit_accounts            0.00
total_debit_limit                    0.00
num_total_cc_accounts                0.00
num_open_cc_accounts                 0.00
num_cc_carrying_balance              0.00
num_mort_accounts                    0.00
account_never_delinq_percent         0.00
tax_liens                            0.00
public_record_bankrupt               0.00
loan_purpose                         0.00
application_type                     0.00
loan_amount                          0.00
term                                 0.00
interest_rate                        0.00
installment                          0.00
grade                                0.00
sub_grade                            0.00
issue_month                          0.00
loan_status                          0.00
initial_listing_status               0.00
disbursement_method                  0.00
balance                              0.00
paid_total                           0.00
paid_principal                       0.00
paid_interest                        0.00
paid_late_fees                       0.00
dtype: float64

In [43]:
df['months_since_last_credit_inquiry']

0        5.0
1        8.0
2        7.0
3       15.0
4        4.0
        ...
9995     6.0
9996     1.0
9997    16.0
9998     5.0
9999    18.0
Name: months_since_last_credit_inquiry, Length: 10000, dtype: float64

## features below are being dropped due to their significantly high proportion of missing values or they are date values.

In [50]:
drop_df = df.drop(['annual_income_joint', 'verification_income_joint', 'debt_to_income_joint', 'months_since_90d_late','months_since_last_credit_inquiry','num_accounts_120d_past_due'],axis=1,inplace=False)
drop_df

KeyError: "['annual_income_joint' 'verification_income_joint' 'debt_to_income_joint'\n 'months_since_90d_late' 'months_since_last_credit_inquiry'\n 'num_accounts_120d_past_due'] not found in axis"

In [49]:
df

,emp_title,emp_length,state,homeownership,annual_income,verified_income,debt_to_income,delinq_2y,months_since_last_delinq,earliest_credit_line,...,sub_grade,issue_month,loan_status,initial_listing_status,disbursement_method,balance,paid_total,paid_principal,paid_interest,paid_late_fees
0,global config engineer,3.0,NJ,MORTGAGE,90000.0,Verified,18.01,0,38.0,2001,...,C3,Mar-2018,Current,whole,Cash,27015.86,1999.33,984.14,1015.19,0.0
1,warehouse office clerk,10.0,HI,RENT,40000.0,Not Verified,5.04,0,118.0,1996,...,C1,Feb-2018,Current,whole,Cash,4651.37,499.12,348.63,150.49,0.0
2,assembly,3.0,WI,RENT,40000.0,Source Verified,21.15,0,28.0,2006,...,D1,Feb-2018,Current,fractional,Cash,1824.63,281.80,175.37,106.43,0.0
3,customer service,1.0,PA,RENT,30000.0,Not Verified,10.16,0,118.0,2007,...,A3,Jan-2018,Current,whole,Cash,18853.26,3312.89,2746.74,566.15,0.0
4,security supervisor,10.0,CA,RENT,35000.0,Verified,57.96,0,118.0,2008,...,C3,Mar-2018,Current,whole,Cash,21430.15,2324.65,1569.85,754.80,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,owner,10.0,TX,RENT,108000.0,Source Verified,22.28,0,118.0,2008,...,A4,Jan-2018,Current,whole,Cash,21586.34,2969.80,2413.66,556.14,0.0
9996,director,8.0,PA,MORTGAGE,121000.0,Verified,32.38,4,9.0,1994,...,D3,Feb-2018,Current,whole,Cash,9147.44,1456.31,852.56,603.75,0.0
9997,toolmaker,10.0,CT,MORTGAGE,67000.0,Verified,45.26,2,6.0,2004,...,E2,Feb-2018,Current,fractional,Cash,27617.65,4620.80,2382.35,2238.45,0.0
9998,manager,1.0,WI,MORTGAGE,80000.0,Source Verified,11.99,0,118.0,1999,...,A1,Feb-2018,Current,whole,Cash,21518.12,2873.31,2481.88,391.43,0.0
9999,operations analyst,3.0,CT,RENT,66000.0,Not Verified,20.82,0,118.0,2005,...,B4,Feb-2018,Current,whole,Cash,11574.83,1658.56,1225.17,433.39,0.0